import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {stateAt,toJD,AU} from '../src/ephemeris.js';
const names=['voyager','mercury','venus','earth','mars','jupiter','saturn','uranus','neptune'];const data=Object.fromEntries(names.map(n=>[n,JSON.parse(fs.readFileSync(new URL('../public/data/'+n+'.json',import.meta.url)))]));
test('All nine NASA datasets have ordered finite state vectors and shared coverage',()=>{for(const d of Object.values(data)){assert.equal(d.source,'NASA JPL Horizons');assert.equal(d.rows[0][0],toJD('1977-09-06'));assert.equal(d.rows.at(-1)[0],toJD('2100-01-01'));assert.ok(d.rows.length>6000);d.rows.forEach((r,i)=>{assert.equal(r.length,7);assert.ok(r.every(Number.isFinite));if(i)assert.ok(r[0]>d.rows[i-1][0]);});}});
test('Hermite reproduces NASA positions and velocities at sample epochs',()=>{for(const d of Object.values(data)){for(let i=0;i<d.rows.length;i+=173){const r=d.rows[i],s=stateAt(d.rows,r[0]);for(let k=0;k<3;k++){assert.ok(Math.abs(s.p[k]-r[k+1])<1e-4);assert.ok(Math.abs(s.v[k]-r[k+4])<1e-8);}}}});
test('Interpolated velocity is the derivative of position',()=>{for(const date of ['1979-03-05T12:03:00Z','1980-11-12T23:03:00Z','2020-01-01T12:00:00Z']){const jd=toJD(date),a=stateAt(data.voyager.rows,jd-1/86400),b=stateAt(data.voyager.rows,jd+1/86400),s=stateAt(data.voyager.rows,jd);for(let k=0;k<3;k++)assert.ok(Math.abs((b.p[k]-a.p[k])/2-s.v[k])<.002);}});
test('Flybys are close to their target planets and produce velocity changes',()=>{for(const [date,name,max] of [['1979-03-05T12:00:00Z','jupiter',600000],['1980-11-12T23:00:00Z','saturn',300000]]){const jd=toJD(date),v=stateAt(data.voyager.rows,jd),p=stateAt(data[name].rows,jd);assert.ok(Math.hypot(...v.p.map((n,i)=>n-p.p[i]))<max);const a=stateAt(data.voyager.rows,jd-2),b=stateAt(data.voyager.rows,jd+2);assert.ok(Math.hypot(...a.v.map((n,i)=>n-b.v[i]))>2);}});
test('2026 state is interstellar and no extrapolation occurs outside coverage',()=>{const rows=data.voyager.rows,s=stateAt(rows,toJD('2026-09-05'));assert.ok(Math.hypot(...s.p)/AU>160);assert.ok(Math.hypot(...s.v)>15&&Math.hypot(...s.v)<20);assert.deepEqual(stateAt(rows,rows.at(-1)[0]+100),stateAt(rows,rows.at(-1)[0]));});

test('NASA predictions keep every body moving after 2026',()=>{for(const d of Object.values(data)){const a=stateAt(d.rows,toJD('2030-01-01')),b=stateAt(d.rows,toJD('2030-01-02'));assert.ok(Math.hypot(...a.p.map((x,i)=>x-b.p[i]))>10000);}});
